const axios = require('axios');
const xml = `<ENVELOPE><HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER><BODY><EXPORTDATA><REQUESTDESC><REPORTNAME>List of Accounts</REPORTNAME><STATICVARIABLES><SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT><ACCOUNTTYPE>Stock Item</ACCOUNTTYPE><SVCURRENTCOMPANY>Nikhil</SVCURRENTCOMPANY></STATICVARIABLES></REQUESTDESC></EXPORTDATA></BODY></ENVELOPE>`;
axios.post('http://127.0.0.1:9000', xml).then(r=>console.log(r.data)).catch(e=>console.log(e));
